# Generated by Django 3.2.9 on 2022-10-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TelegramUser',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
