# Generated by Django 3.2.9 on 2022-10-16 21:25

from django.db import migrations, models
import django.db.models.deletion
import food_tickets.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221016_2020'),
        ('food_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='secret_code',
            field=models.CharField(blank=True, default=food_tickets.utils.random_secret_code, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser'),
        ),
    ]
