# Generated by Django 3.2.9 on 2022-10-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_tickets', '0003_alter_student_telegram_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodaccesslog',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='has_food_right',
            field=models.BooleanField(default=False, verbose_name='Есть ли право на еду (он льготник/платит за нее?)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='FoodTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField(verbose_name='Время истечения')),
                ('type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед')], max_length=16, verbose_name='Тип тикета')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodticket_owner', to='food_tickets.student', verbose_name='Пользователь тикета')),
                ('ticket_sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_tickets.student', verbose_name='Спонсор тикета')),
            ],
        ),
        migrations.AddField(
            model_name='foodaccesslog',
            name='food_ticket',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='food_tickets.foodticket'),
            preserve_default=False,
        ),
    ]
