# Generated by Django 3.2.9 on 2022-10-18 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_tickets', '0004_auto_20221018_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodticket',
            name='time_created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 18, 20, 13, 32, 891673)),
            preserve_default=False,
        ),
    ]
