# Generated by Django 3.2.9 on 2022-10-21 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_tickets', '0005_foodticket_time_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodticket',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='foodticket',
            name='date_usable_at',
            field=models.DateField(default=datetime.date(2022, 10, 21), verbose_name='День, когда этот тикет можно использовать'),
            preserve_default=False,
        ),
    ]
