# Generated by Django 3.2.9 on 2022-10-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_tickets', '0006_auto_20221021_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodaccesslog',
            old_name='time',
            new_name='datetime_created',
        ),
    ]
