# Generated by Django 3.2.9 on 2022-10-28 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_tickets', '0007_rename_time_foodaccesslog_datetime_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
