KOMARU_PACK = {
    "DAMN": "CAACAgIAAxkBAAEGNtZjWmr2jjRNt-SBngJG7JF2JI5FDgACJBwAAvN_0EoFF9MvTVVmvioE",
    "1000_WORDS": "CAACAgIAAxkBAAEGNthjWmsLrsD78hUgyPURDJ5W-36u0gAChyAAAqZ-2EqanJbxh54xuioE",
    "IN_THIS_GROUP": "CAACAgIAAxkBAAEGNtpjWmshlPBez9WIxadrEUn9TUU9UAACpB4AAozf2UpUm1gdIGZP-CoE",
    "SYNCHRONIZATION": "CAACAgIAAxkBAAEGNtxjWms1FBrYatXgJJp-YYvFMX3nRwACKyEAAtby0UqAtwABGrUK4V4qBA",
    "WHAT": "CAACAgIAAxkBAAEGNt5jWmtZxnQ0g8w6M1KTDL7W7rrSlAACnSAAAiQX0UqVVhLD9WnjtCoE",
    "NOT_OBLIGATED": "CAACAgIAAxkBAAEGNuBjWmtoRSu1tqVrXXYOmDyI0KLrYQAC9R0AAkgJ0Ur99wTyFfGAFSoE",
    "CHILL": "CAACAgIAAxkBAAEGNuJjWmuFmunSirZtpzwIXNrHYjIWvgACxiAAArtw2EoLuZs_en41tSoE",
    "TELL_MORE": "CAACAgIAAxkBAAEGNuRjWmuRPl987FHbnpZj6PJDRokfSAACAycAAmEW0UqA15jWx-MpcSoE",
    "WHAT_TO_DO": "CAACAgIAAxkBAAEGNuZjWmul0btIFdEl0DLAdBqrPxO9WwACsiQAAo9i2Eoaao5LZ9_HSCoE",
    "ADMIN_WORKING": "CAACAgIAAxkBAAEGNuhjWmuzjU4zgo5ouo66QlJ1pT5ZlQACLiIAArhv0UryBUEnf6VZ9CoE",
}
