name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - id: deploy
      name: Deploy to dokku
      uses: vitalyliber/dokku-github-action@v7.0
      with:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.SSH_PORT }}
          PROJECT: 'dtb'
          FORCE_DEPLOY: true
          
