name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: deploy
      name: Deploy to dokku
      uses: vitalyliber/dokku-github-action@v7.0
      env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: s2.zloserver.com
          PORT: 34001
          PROJECT: 'dtb'
          FORCE_DEPLOY: true
          
